### ISSUE TITLE
Integrate 3dmol visualizer into React frontend

### ISSUE THREAD

**Issue by Eo300** [Electrostatics/apbs-web#4]
For the [AWS](https://github.com/Electrostatics/apbs-web/tree/aws) branch, integrate 3dmol visualizer to be usable within React, as opposed to current implementation which [serves the page through Flask](https://github.com/Electrostatics/apbs-rest/tree/master/src/visualizer-legacy)

**Comment by intendo** [comment]
@sobolevnrm 

@Eo300 was taking the output of APBS to create a DX format and then converting that to Cube format for loading the data into 3dmol.
It turns out that 3dmol can read the DX format so there no reason to run dx2cube.py for the Web app.
  
We were thinking it would be 1 less process and 1 less file to generate and 2 fewer points of possible failure if we eliminate converting from DX to Cube format.
We have the 3dmol capability working in the APBS/PDB2PQR Web app and it reads in the OpenDX format written out by APBS.
 
Can we eliminate the dx2cube capability and any further support for the cube format?

**Comment by sobolevnrm** [comment]
Sounds good to me -- I would still like to provide a DX conversion tool in
Python along with the main APBS code.
